
name: download_and_process
description: download_and_process
inputs:
  test_input:
    description: key
    required: true
  test_input2:
    description: key2
    required: false
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      shell: bash
    - name: get cache
      uses: actions/cache/restore@v4
      with:
        path: |
          B_instruments_*.csv
        key: B_instruments
    - name: get secrets
      uses: oNaiPs/secrets-to-env-action@v1
      with:
        secrets: ${{ toJSON(secrets) }}
    - run: |
        pip install -r requirements.txt
        python B/instruments_process.py ${{ inputs.test_input }}
      shell: bash
    - name: "cache1"
      uses: actions/cache/save@v4
      with:
        path: |
          B_instruments_${{ inputs.test_input }}.csv
        key: B_instruments-cap