name: test-action
description: test action
inputs:
  test_input:
    description: key
    required: true
  test_input2:
    description: key2
    required: false
runs:
  using: composite
  steps:
    - name: echo test
      shell: bash
      run: |
        echo ${{inputs.test_input}}