
name: download_and_process
description: download_and_process
inputs:
  test_input:
    description: key
    required: true
  test_input2:
    description: key2
    required: false
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: get cache
      uses: actions/cache/restore@v4
      with:
        path: |
          B_instruments_*.csv
        key: B_instruments
    - name: get secrets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        B_INSTRUMENT_DOWNLOAD_URL1: https://api.bseindia.com/BseIndiaAPI/api/LitsOfScripCSVDownload/w?segment=Equity&status=&industry=&Group=&Scripcode=
        B_INSTRUMENT_DOWNLOAD_URL2: https://api.bseindia.com/BseIndiaAPI/api/LitsOfScripCSVDownload/w?segment=EQT0&status=&industry=&Group=&Scripcode=
        B_SEARCH_CAP: https://www.bseindia.com/corporates/Sharehold_Searchnew.aspx
      run: |
        pip install -r requirements.txt
        python B_instruments_process.py ${{ inputs.test_input }}
      shell: bash
    - name: "cache1"
      uses: actions/cache/save@v4
      with:
        path: |
          B_instruments_${{ inputs.test_input }}.csv
        key: B_instruments-cap