
name: download_and_process
description: download_and_process
inputs:
  test_input:
    description: key
    required: true
  test_input2:
    description: key2
    required: false
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: get cache
      uses: actions/cache/restore@v4
      with:
        path: |
          N_instruments_*.csv
        key: N_instruments
    - name: get secrets
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        SUBMIT_URL: ${{ secrets.SUBMIT_URL }}
        NSE_INIT: ${{ secrets.NSE_INIT }}
        NSE_EQUITY: ${{ secrets.NSE_EQUITY }}
        NSE_MAIN: ${{ secrets.NSE_MAIN }}
        NSE_SHARE_PATTERN: ${{ secrets.NSE_SHARE_PATTERN }}
        N_SUBMIT_URL: ${{ secrets.N_SUBMIT_URL }}
      run: |
        pip install -r requirements.txt
        python N_instruments_process.py ${{ inputs.test_input }}
      shell: bash
    - name: "cache1"
      uses: actions/cache/save@v4
      with:
        path: |
          N_instruments_${{ inputs.test_input }}.csv
        key: N_instruments_cap_${{ inputs.test_input }}