name: B_block_download
on:
    workflow_dispatch:
    schedule:
        - cron: '0 * * * *'
permissions:
    actions: write
    id-token: write
    contents: write
jobs:
    download:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: N Block Download
              env:
                BLOCK_SUBMIT_URL: ${{ secrets.BLOCK_SUBMIT_URL }}
                JWT_SECRET: ${{ secrets.JWT_SECRET }}
                BSE_BULK_DEALS: ${{ secrets.BSE_BULK_DEALS }}
              run: |
                  pip install -r requirements.txt
                  python3 B_bulk_block_deals_downloader.py
                  