name: B_instrument_download_and_process
on:
    workflow_dispatch:
permissions:
    actions: write
    id-token: write
    contents: write
jobs:
    download:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: delete existing cache
              continue-on-error: true
              run: |
                      gh cache delete --all
              env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: get secrets
              uses: oNaiPs/secrets-to-env-action@v1
              with:
                secrets: ${{ toJSON(secrets) }}
            - run: |
                pip install -r requirements.txt
                python B/instruments.py
            - name: "cache1"
              uses: actions/cache/save@v4
              with:
                path: |
                    B_instruments_*.csv
                key: B_instruments
    process1:
        runs-on: ubuntu-latest
        needs: download
        steps:
            - name: pwd
              run: pwd
            - name: list 
              run: ls -laR
            - name: test-action
              uses: ./.github/process
              with:
                test_input: 1
        
