name: B_instrument_download
on:
    workflow_dispatch:
permissions:
    contents: write
jobs:
    download:
        runs-on: ubuntu-latest
        environment: B_download
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: get secrets
              uses: oNaiPs/secrets-to-env-action@v1
              with:
                secrets: ${{ toJSON(secrets) }}
            - run: |
                printenv
                pip install -r requirements.txt
                python B/instruments.py
