name: B_instrument_download_and_process
on:
    workflow_dispatch:
permissions:
    actions: write
    id-token: write
    contents: write
jobs:
    download:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: delete existing cache
              continue-on-error: true
              run: |
                      gh cache delete --all
              env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: get secrets
              uses: oNaiPs/secrets-to-env-action@v1
              with:
                secrets: ${{ toJSON(secrets) }}
            - run: |
                pip install -r requirements.txt
                python B_instruments.py
            - name: "cache1"
              uses: actions/cache/save@v4
              with:
                path: |
                    B_instruments_*.csv
                key: B_instruments
    process1:
        runs-on: ubuntu-latest
        needs: download
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: test-action
              uses: ./.github/process
              with:
                test_input: 1
    process2:
        runs-on: ubuntu-latest
        needs: download
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: test-action
              uses: ./.github/process
              with:
                test_input: 2
    process3:
        runs-on: ubuntu-latest
        needs: download
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: test-action
              uses: ./.github/process
              with:
                test_input: 3
    process4:
        runs-on: ubuntu-latest
        needs: download
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: test-action
              uses: ./.github/process
              with:
                test_input: 4
    process5:
        runs-on: ubuntu-latest
        needs: download
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: test-action
              uses: ./.github/process
              with:
                test_input: 5
    process6:
        runs-on: ubuntu-latest
        needs: download
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: test-action
              uses: ./.github/process
              with:
                test_input: 6
    process7:
        runs-on: ubuntu-latest
        needs: download
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: test-action
              uses: ./.github/process
              with:
                test_input: 7
    process8:
        runs-on: ubuntu-latest
        needs: download
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: test-action
              uses: ./.github/process
              with:
                test_input: 8
    process9:
        runs-on: ubuntu-latest
        needs: download
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: test-action
              uses: ./.github/process
              with:
                test_input: 9
    process10:
        runs-on: ubuntu-latest
        needs: download
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: test-action
              uses: ./.github/process
              with:
                test_input: 10
    process11:
        runs-on: ubuntu-latest
        needs: download
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: test-action
              uses: ./.github/process
              with:
                test_input: 11
    process12:
        runs-on: ubuntu-latest
        needs: download
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: test-action
              uses: ./.github/process
              with:
                test_input: 12
    process13:
        runs-on: ubuntu-latest
        needs: download
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: test-action
              uses: ./.github/process
              with:
                test_input: 13
    process14:
        runs-on: ubuntu-latest
        needs: download
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: test-action
              uses: ./.github/process
              with:
                test_input: 14
    process15:
        runs-on: ubuntu-latest
        needs: download
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: test-action
              uses: ./.github/process
              with:
                test_input: 15
    process16:
        runs-on: ubuntu-latest
        needs: download
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: test-action
              uses: ./.github/process
              with:
                test_input: 16
    process17:
        runs-on: ubuntu-latest
        needs: download
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: test-action
              uses: ./.github/process
              with:
                test_input: 17
    process18:
        runs-on: ubuntu-latest
        needs: download
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: test-action
              uses: ./.github/process
              with:
                test_input: 18
    process19:
        runs-on: ubuntu-latest
        needs: download
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: test-action
              uses: ./.github/process
              with:
                test_input: 19
    combine:
        runs-on: ubuntu-latest
        needs: [process1, process2, process3, process4, process5, process6, process7, process8, process9, process10, process11, process12, process13, process14, process15, process16, process17, process18, process19]
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - uses: almahmoud/multi-cache-restore-action@main
              name: Multi-cache
              with:
                keys: "'B_instruments_cap_1','B_instruments_cap_2','B_instruments_cap_3','B_instruments_cap_4','B_instruments_cap_5','B_instruments_cap_6','B_instruments_cap_7','B_instruments_cap_8','B_instruments_cap_9','B_instruments_cap_10','B_instruments_cap_11','B_instruments_cap_12','B_instruments_cap_13','B_instruments_cap_14','B_instruments_cap_15','B_instruments_cap_16','B_instruments_cap_17','B_instruments_cap_18','B_instruments_cap_19"
                paths: "'./B_instruments_1.csv','./B_instruments_2.csv','./B_instruments_3.csv','./B_instruments_4.csv','./B_instruments_5.csv','./B_instruments_6.csv','./B_instruments_7.csv','./B_instruments_8.csv','./B_instruments_9.csv','./B_instruments_10.csv','./B_instruments_11.csv','./B_instruments_12.csv','./B_instruments_13.csv','./B_instruments_14.csv','./B_instruments_15.csv','./B_instruments_16.csv','./B_instruments_17.csv','./B_instruments_18.csv','./B_instruments_19.csv'"            
            - name: combine
              run: |
                    pip install -r requirements.txt
                    python B_instruments_combine.py