name: N_block_download
on:
    workflow_dispatch:
permissions:
    actions: write
    id-token: write
    contents: write
jobs:
    download:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: N Block Download
              env:
                BLOCK_SUBMIT_URL: ${{ secrets.BLOCK_SUBMIT_URL }}
                JWT_SECRET: ${{ secrets.JWT_SECRET }}
                NSE_BULK_DEALS: ${{ secrets.NSE_BULK_DEALS }}
                NSE_BLOCK_DEALS: ${{ secrets.NSE_BLOCK_DEALS }}
                NSE_MAIN: ${{ secrets.NSE_MAIN }}
              run: |
                  pip install -r requirements.txt
                  python3 N_bulk_block_deals_downloader.py
                  